name: Continue Website Deployment
on:
    workflow_dispatch: 
    push:
      branches:
        - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run:  |
              cd fourth-action-react-demo
              npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Load & cache dependencies
        id: check-cache-status
        uses: ./.github/actions/cached-deps
        with:
          cache-check: 'false'
      - name: output cache data
        run: echo "${{ steps.check-cache-status.outputs.used-cache }}"
      - name: Test code
        id: test-stage
        continue-on-error: true # treats stage as success even it failed
        run: |
              cd fourth-action-react-demo
              npm run test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: fourth-action-react-demo/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        id: build-website
        run: |
              cd fourth-action-react-demo
              npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: fourth-action-react-demo/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist-files
      - name: Output contents
        run: |
              cd $GITHUB_WORKSPACE/dist-files
              ls
      - name: Deploy
        run: echo "Deploying..."
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run github action
        uses: ./.github/actions/deploy-s3-javascript
  report:
    if: failure()
    needs: [lint,deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: |
              echo 'Display info'
              echo '${{ toJson(github)}}'